Constants = {
    cities: [
        {city: 'New York', state: 'NY'},
        {city: 'Los Angeles', state: 'CA'},
        {city: 'Chicago', state: 'IL'},
        {city: 'Houston', state: 'TX'},
        {city: 'Philadelphia', state: 'PA'},
        {city: 'Phoenix', state: 'AZ'},
        {city: 'San Antonio', state: 'TX'},
        {city: 'San Diego', state: 'CA'},
        {city: 'Dallas', state: 'TX'},
        {city: 'San Jose', state: 'CA'},
        {city: 'Austin', state: 'TX'},
        {city: 'Indianapolis', state: 'IN'},
        {city: 'Jacksonville', state: 'FL'},
        {city: 'San Francisco', state: 'CA'},
        {city: 'Columbus', state: 'OH'},
        {city: 'Charlotte', state: 'NC'},
        {city: 'Fort Worth', state: 'TX'},
        {city: 'Detroit', state: 'MI'},
        {city: 'El Paso', state: 'TX'},
        {city: 'Memphis', state: 'TN'},
        {city: 'Seattle', state: 'WA'},
        {city: 'Denver', state: 'CO'},
        {city: 'Washington', state: 'MD'}, // exception
        {city: 'Boston', state: 'MA'},
        {city: 'Nashville', state: 'TN'},
        {city: 'Baltimore', state: 'MD'},
        {city: 'Oklahoma City', state: 'OK'},
        {city: 'Louisville', state: 'KY'},
        {city: 'Portland', state: 'OR'},
        {city: 'Las Vegas', state: 'NV'},
        {city: 'Milwaukee', state: 'WI'},
        {city: 'Albuquerque', state: 'NM'},
        {city: 'Fresno', state: 'CA'},
        {city: 'Sacramento', state: 'CA'},
        {city: 'Long Beach', state: 'CA'},
        {city: 'Kansas City', state: 'MO'},
        {city: 'Mesa', state: 'AZ'},
        {city: 'Virginia Beach', state: 'VA'},
        {city: 'Atlanta', state: 'GA'},
        {city: 'Colorado Springs', state: 'CO'},
        {city: 'Omaha', state: 'NE'},
        {city: 'Raleigh', state: 'NC'},
        {city: 'Miami', state: 'FL'},
        {city: 'Oakland', state: 'CA'},
        {city: 'Minneapolis', state: 'MN'},
        {city: 'Tulsa', state: 'OK'},
        {city: 'Cleveland', state: 'OH'},
        {city: 'Wichita', state: 'KS'},
        {city: 'Arlington', state: 'TX'}
    ]
};